name: Build and Tag

on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create a release tag
        env:
          GITHUB_TOKEN: ${{ secrets.TAG_GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

          # 当日日期
          DATE=$(date +"%Y_%m_%d")

          # 当前分支
          CURRENT_BRANCH="release"

          # 获取最新版本号
          LATEST_TAG=$(git tag -l "${CURRENT_BRANCH}_${DATE}_v*" | sort -V | tail -n1)
          # 如果今天还没有版本, 从v1开始
          if [ -z "$LATEST_TAG" ]; then
              VERSION=1
          else
              # 提取现有的最大版本
              VERSION=${LATEST_TAG#*v}
              # 递增版本号
              ((VERSION++))
          fi

          # 创建新的标签名
          TAG_NAME="${CURRENT_BRANCH}_${DATE}_v${VERSION}"

          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "Created new tag: $TAG_NAME"
